"use client";

import { FormEvent, useEffect, useState } from "react";

type Announcement = { id: number; title: string; summary: string; eventDate?: string; location?: string };
type Media = { id: number; title: string; type: string; url: string; thumbnailUrl?: string; caption?: string };

export default function Home() {
  const [content, setContent] = useState<{ announcements: Announcement[]; media: Media[] }>({ announcements: [], media: [] });
  const [sending, setSending] = useState(false), [sent, setSent] = useState(false), [formError, setFormError] = useState("");
  const [video, setVideo] = useState<Media | null>(null), [menu, setMenu] = useState(false);
  useEffect(() => { fetch("/api/content").then((r) => r.ok ? r.json() : null).then((data) => data && setContent(data)).catch(() => {}); }, []);

  async function join(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSending(true); setFormError(""); const form = new FormData(event.currentTarget);
    const response = await fetch("/api/join", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) });
    const result = await response.json(); setSending(false); if (response.ok) { setSent(true); event.currentTarget.reset(); } else setFormError(result.error || "No pudimos enviar el formulario.");
  }

  return <main>
    <header className="site-header">
      <a className="brand" href="#inicio" aria-label="Coro FIUBA, inicio"><img src="/logo-fiuba.png" alt="" /><span><strong>Coro FIUBA</strong><small>Universidad de Buenos Aires</small></span></a>
      <nav className={menu ? "open" : ""} aria-label="Navegación principal"><a href="#nosotros" onClick={() => setMenu(false)}>El coro</a><a href="#ciclo" onClick={() => setMenu(false)}>Ciclo de conciertos</a><a href="#agenda" onClick={() => setMenu(false)}>Agenda</a><a href="#archivo" onClick={() => setMenu(false)}>Archivo</a></nav>
      <a className="nav-cta" href="#sumate">Sumate al coro <span>↗</span></a><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Abrir menú" aria-expanded={menu}>{menu ? "×" : "☰"}</button>
    </header>

    <section className="hero" id="inicio"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><p className="eyebrow"><span /> Facultad de Ingeniería · UBA</p><h1>Ingeniería<br />en <em>armonía.</em></h1><p className="hero-lede">Un espacio donde las voces, la música y la comunidad universitaria se encuentran.</p><div className="hero-actions"><a className="button button-gold" href="#sumate">Quiero participar <span>→</span></a><a className="text-link" href="#nosotros">Conocé al coro <span>↓</span></a></div></div><div className="hero-mark"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><img src="/logo-fiuba.png" alt="Logo del Coro de la Facultad de Ingeniería de la UBA" /><p><span>Desde la facultad</span><strong>Una voz colectiva</strong></p></div><div className="hero-foot"><span>Buenos Aires, Argentina</span><div className="sound-wave" aria-label="Representación de una onda sonora">{Array.from({ length: 18 }, (_, i) => <i key={i} style={{ height: `${10 + ((i * 13) % 26)}px` }} />)}</div><span>Cultura · Comunidad · Música</span></div></section>

    <section className="manifesto" id="nosotros"><p className="section-index">01 — El coro</p><div><p className="eyebrow dark"><span /> Muchas voces, una obra</p><h2>Respirar juntos.<br /><em>Construir sonido.</em></h2><p>El Coro FIUBA es un punto de encuentro entre la disciplina de la ingeniería y la sensibilidad de la música coral. Una comunidad abierta que ensaya, aprende y transforma cada partitura en una experiencia compartida.</p></div><div className="column-study" aria-hidden="true"><i /><i /><i /><i /><i /><span>Voces que hacen universidad</span></div></section>

    <section className="concert-cycle" id="ciclo"><div className="cycle-intro"><p className="section-index">02 — Ciclo de conciertos</p><p className="eyebrow dark"><span /> Una tradición desde los años 90</p><h2>La facultad<br /><em>abre sus puertas.</em></h2><p>El Ciclo de Conciertos de la Facultad de Ingeniería de la UBA fue iniciado por el anterior director del Coro, el Maestro Marcelo Ortiz Rocca. Esa tradición continúa hasta hoy, reuniendo cada año a coros del ámbito cultural y universitario.</p></div><div className="cycle-program"><p className="cycle-kicker">Tres encuentros anuales</p><div className="cycle-dates"><article><span>Oct.</span><strong>Último sábado</strong></article><article><span>Nov.</span><strong>Último sábado</strong></article><article><span>Dic.</span><strong>Segundo sábado</strong></article></div><div className="cycle-venue"><div><small>Horario habitual</small><strong>18:00 — 20:00 h <em>aprox.</em></strong></div><div><small>Sede</small><a href="https://www.fi.uba.ar/institucional/sedes/las-heras" target="_blank" rel="noreferrer"><strong>Av. Las Heras 2214</strong><span>Ver ubicación ↗</span></a></div></div><p className="cycle-note">Organizado por el Coro FIUBA, el ciclo invita a distintas agrupaciones corales a compartir repertorios, experiencias y comunidad.</p></div></section>

    <section className="agenda" id="agenda"><div className="section-heading"><div><p className="eyebrow"><span /> 03 — Actualidad</p><h2>Próximas<br />notas.</h2></div><p>Anuncios, conciertos y novedades de nuestra actividad coral.</p></div><div className="announcement-list">{content.announcements.length ? content.announcements.map((item, index) => <article key={item.id}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{item.eventDate ? new Date(item.eventDate + "T12:00:00").toLocaleDateString("es-AR", { day: "2-digit", month: "long", year: "numeric" }) : "Novedad"}</small><h3>{item.title}</h3><p>{item.summary}</p></div><div className="announcement-place">{item.location || "Coro FIUBA"}<b>↗</b></div></article>) : <div className="agenda-empty"><span>♪</span><div><h3>Nueva temporada, nuevos encuentros</h3><p>Pronto vamos a publicar acá conciertos, ensayos abiertos y todas las novedades del coro.</p></div></div>}</div></section>

    <section className="archive" id="archivo"><div className="archive-heading"><p className="section-index">04 — Archivo vivo</p><h2>Escuchanos.<br /><em>Miranos.</em></h2><p>Conciertos, ensayos y momentos que forman nuestra memoria colectiva.</p></div><div className="media-grid">{content.media.length ? content.media.map((item, index) => <button className={`media-card media-${index % 3}`} key={item.id} onClick={() => item.type === "youtube" || item.type === "video" ? setVideo(item) : undefined}>{item.type === "image" ? <img src={item.url} alt={item.title} /> : item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" /> : <div className="media-placeholder"><img src="/logo-fiuba.png" alt="" /></div>}<span className="media-type">{item.type === "youtube" || item.type === "video" ? "▶ Ver video" : "Fotografía"}</span><strong>{item.title}</strong>{item.caption && <small>{item.caption}</small>}</button>) : <><div className="media-card media-placeholder-card"><div className="media-placeholder"><img src="/logo-fiuba.png" alt="" /></div><span className="media-type">Archivo coral</span><strong>Muy pronto, nuestra historia en imágenes</strong><small>Las fotos y videos se gestionan desde el panel editorial.</small></div><div className="archive-note"><span>♫</span><p>Este espacio va a crecer con cada concierto, cada ensayo y cada encuentro.</p></div></>}</div></section>

    <section className="join" id="sumate"><div className="join-intro"><p className="section-index">05 — Sumate</p><p className="eyebrow"><span /> Tu voz también construye</p><h2>Hay un lugar<br />para <em>vos.</em></h2><p>Si te interesa cantar y ser parte de una experiencia colectiva, completá el formulario. No hace falta pertenecer a la FIUBA.</p><div className="join-details"><div><small>Ensayos</small><strong>Todos los viernes · 19:30 a 22:00 h</strong></div><div><small>Lugar</small><a href="https://www.fi.uba.ar/institucional/sedes/paseo-colon" target="_blank" rel="noreferrer"><strong>Av. Paseo Colón 850 · CABA</strong><span>Ver sede ↗</span></a></div></div></div><form className="join-form" id="formulario" onSubmit={join}><div className="form-number">Formulario de participación <span>01 / 01</span></div><div className="form-row"><label>Nombre y apellido *<input name="fullName" required autoComplete="name" placeholder="¿Cómo te llamás?" /></label><label>Email *<input name="email" required type="email" autoComplete="email" placeholder="tu@email.com" /></label></div><div className="form-row"><label>Teléfono<input name="phone" autoComplete="tel" placeholder="11 0000 0000" /></label><label>Edad<input name="age" type="number" min="16" max="99" placeholder="—" /></label></div><div className="form-row"><label>Registro de voz<select name="voice"><option value="">No estoy seguro/a</option><option>Soprano</option><option>Contralto</option><option>Tenor</option><option>Bajo</option></select></label><label>Experiencia previa<select name="experience"><option value="">Elegí una opción</option><option>Sin experiencia</option><option>Algo de experiencia</option><option>Experiencia coral</option></select></label></div><label>Contanos algo sobre vos<textarea name="message" rows={4} placeholder="¿Qué te acerca al canto coral?" /></label><label className="consent"><input type="checkbox" required /> <span>Acepto que el Coro FIUBA use estos datos para contactarme sobre la convocatoria.</span></label><button className="button button-gold" disabled={sending}>{sending ? "Enviando…" : "Enviar solicitud"}<span>→</span></button>{sent && <p className="success-message">¡Gracias! Recibimos tus datos. Pronto nos vamos a poner en contacto.</p>}{formError && <p className="error-message">{formError}</p>}</form></section>

    <footer><div className="footer-brand"><img src="/logo-fiuba.png" alt="Logo Coro FIUBA" /><h2>Coro FIUBA</h2><p>Facultad de Ingeniería · Universidad de Buenos Aires</p></div><div><small>Navegación</small><a href="#nosotros">El coro</a><a href="#ciclo">Ciclo de conciertos</a><a href="#agenda">Agenda</a><a href="#archivo">Archivo</a><a href="#sumate">Sumate</a></div><div><small>Encontranos</small><a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://youtube.com" target="_blank" rel="noreferrer">YouTube ↗</a><a href="mailto:coro@fi.uba.ar">Email ↗</a></div><div className="footer-admin"><small>Gestión</small><a href="/admin">Panel editorial →</a></div><p className="copyright">© 2026 Coro FIUBA · Buenos Aires, Argentina</p></footer>

    {video && <div className="modal" role="dialog" aria-modal="true" aria-label={video.title} onClick={() => setVideo(null)}><button className="modal-close" onClick={() => setVideo(null)} aria-label="Cerrar video">×</button><div className="video-frame" onClick={(e) => e.stopPropagation()}>{video.type === "youtube" ? <iframe src={video.url} title={video.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /> : <video src={video.url} controls autoPlay />}<h3>{video.title}</h3></div></div>}
  </main>;
}
