"use client";
import { useEffect, useState } from "react";
type Media = { id:number; title:string; type:string; url:string; thumbnailUrl?:string; caption?:string };

export default function ArchiveContent() {
  const [items,setItems] = useState<Media[]>([]), [video,setVideo] = useState<Media|null>(null);
  useEffect(() => { fetch("/api/content").then(r => r.ok ? r.json() : null).then(data => data && setItems(data.media)).catch(() => {}); }, []);
  return <><section className="page-hero"><div className="page-hero-grid" aria-hidden="true" /><p className="section-index">04 — Archivo vivo</p><div><p className="eyebrow"><span /> Nuestra memoria</p><h1>Escuchanos.<br /><em>Miranos.</em></h1></div><p className="page-intro">Conciertos, ensayos y momentos que forman nuestra historia colectiva.</p></section><section className="archive-page"><div className="media-grid">{items.length ? items.map((item,index) => <button className={`media-card media-${index%3}`} key={item.id} onClick={() => item.type !== "image" && setVideo(item)}>{item.type === "image" ? <img src={item.url} alt={item.title} /> : item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" /> : <div className="media-placeholder"><img src="/logo-fiuba.png" alt="" /></div>}<span>{item.type === "image" ? "Fotografía" : "▶ Ver video"}</span><strong>{item.title}</strong>{item.caption && <small>{item.caption}</small>}</button>) : <><div className="media-card featured"><div className="media-placeholder"><img src="/logo-fiuba.png" alt="" /></div><span>Archivo coral</span><strong>Muy pronto, nuestra historia en imágenes</strong><small>Las fotos y videos se gestionan desde el panel editorial.</small></div><div className="archive-note"><b>♫</b><p>Este espacio va a crecer con cada concierto, ensayo y encuentro.</p></div></>}</div></section>{video && <div className="modal" role="dialog" aria-modal="true" aria-label={video.title} onClick={() => setVideo(null)}><button className="modal-close" onClick={() => setVideo(null)} aria-label="Cerrar video">×</button><div className="video-frame" onClick={e => e.stopPropagation()}>{video.type === "youtube" ? <iframe src={video.url} title={video.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /> : <video src={video.url} controls autoPlay />}<h2>{video.title}</h2></div></div>}</>;
}
