import PageHero from "@/app/components/PageHero";
import SiteFooter from "@/app/components/SiteFooter";
import SiteHeader from "@/app/components/SiteHeader";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("El coro", "Conocé la historia, las direcciones, el repertorio y la comunidad del Coro FIUBA desde la década del 60.");

export default function ChoirPage() {
  return <main><SiteHeader /><PageHero index="01 — El coro" eyebrow="Muchas voces, una obra" title="Respirar juntos." italic="Construir sonido." intro="Un punto de encuentro entre la disciplina de la ingeniería y la sensibilidad de la música coral." />
    <section className="editorial-split"><div className="large-number">01</div><div><h2>Voces que hacen<br />universidad.</h2><p>El Coro FIUBA es una comunidad abierta que ensaya, aprende y transforma cada partitura en una experiencia compartida. La escucha, el trabajo colectivo y el compromiso son parte de nuestra manera de hacer música.</p><p>No hace falta pertenecer a la Facultad para participar. Nos convoca el deseo de cantar, crecer musicalmente y construir un sonido común.</p></div><aside><div className="column-study" aria-hidden="true"><i /><i /><i /><i /><i /></div><small>Música · Formación · Comunidad</small></aside></section>
    <section className="values-band"><article><span>01</span><h3>Escucha</h3><p>Cada voz encuentra su lugar atendiendo a las demás.</p></article><article><span>02</span><h3>Disciplina</h3><p>El ensayo transforma el esfuerzo individual en obra colectiva.</p></article><article><span>03</span><h3>Encuentro</h3><p>La música abre un espacio de comunidad dentro y fuera de la Facultad.</p></article></section>
    <section className="choir-history"><div className="history-heading"><p className="section-index">Historia</p><p className="eyebrow dark"><span /> Desde la década del 60</p><h2>Más de medio siglo<br /><em>haciendo música.</em></h2><p>El Coro de la Facultad de Ingeniería fue creado por el Departamento de Cultura de la FIUBA. Desde entonces, distintas generaciones construyeron una identidad coral que forma parte de la vida cultural de la Universidad.</p></div><div className="director-timeline"><article><span>Década del 60</span><div><small>Creación y primera dirección</small><h3>Virtú Maragno</h3><p>El Departamento de Cultura de la FIUBA crea el Coro de la Facultad de Ingeniería.</p></div></article><article><span>Década del 80</span><div><small>Dirección hasta 1988</small><h3>Rolando Depiaggi</h3><p>Asume la conducción y dirige el Coro durante la década.</p></div></article><article><span>1995</span><div><small>Dirección musical</small><h3>Marcelo Ortiz Rocca</h3><p>Inicia una nueva etapa y el Coro comienza a organizar el Ciclo de Conciertos Corales de la FIUBA.</p></div></article><article className="current"><span>Desde 2023</span><div><small>Dirección actual</small><h3>Carolina Abbamonte</h3><p>Directora, junto a Lurdes Sabeckis como subdirectora.</p></div></article></div></section>
    <section className="choir-profile"><div><p className="section-index">La comunidad</p><h2>Una formación<br />abierta y diversa.</h2></div><div className="profile-copy"><p>El Coro está integrado por estudiantes, profesores, profesoras y personas egresadas de la FIUBA, y está abierto a toda la comunidad.</p><p>Su repertorio recorre distintos géneros: desde la música coral clásica hasta expresiones populares y contemporáneas.</p><div className="repertoire-tags"><span>Clásica</span><span>Popular</span><span>Contemporánea</span></div></div></section>
    <section className="milestones"><div className="milestones-intro"><p className="eyebrow"><span /> Premios y presentaciones</p><h2>Una historia que<br />viajó y resonó.</h2><p>El Coro participó en encuentros de todo el país y obtuvo numerosos premios y reconocimientos.</p></div><div className="milestone-list"><article><span>1998</span><div><h3>Eisteddfod de Trelew</h3><p>Participó del Concurso Internacional Eisteddfod, en Chubut, y obtuvo cuatro primeros premios para coro mixto. Se destacaron las categorías principales de Música Universal y Música Galesa: fue la primera vez en 104 años que un coro ajeno a la comunidad galesa obtuvo el primer premio en esta última categoría.</p></div></article><article><span>2002</span><div><h3>Siete primeros premios</h3><p>Regresó al Concurso Internacional Eisteddfod, intervino en once categorías y obtuvo siete primeros premios.</p></div></article><article><span>2004</span><div><h3>Teatro Colón</h3><p>Presentó la Novena Sinfonía de Beethoven en dos conciertos en la sala principal, junto a la Orquesta Académica del Teatro Colón.</p></div></article><article><span>2005</span><div><h3>Beethoven en tres ciudades</h3><p>Interpretó la Novena Sinfonía en el Teatro Avenida de Buenos Aires, el Teatro Municipal de Olavarría y la ciudad de San Nicolás.</p></div></article><article><span>2015</span><div><h3>Olavarría y Ballena Azul</h3><p>Volvió a interpretar la Novena Sinfonía en el Teatro Municipal de Olavarría y en la Sala Ballena Azul del Centro Cultural Kirchner, junto a la Orquesta Sinfónica Municipal de Olavarría y otros coros.</p></div></article><article><span>2016</span><div><h3>Festival Coral de Gualeguay</h3><p>Se presentó en este encuentro coral de realización anual.</p></div></article></div></section>
    <section className="page-cta"><div><p className="eyebrow"><span /> Ensayamos cada viernes</p><h2>¿Querés cantar<br />con nosotros?</h2></div><a className="button button-gold" href="/sumate">Conocé la convocatoria <span>→</span></a></section><SiteFooter /></main>;
}
